const countryList = {
    AED: ["AE", "AED - Emirati Dhiram"], 
    AFN: ["AF", "AFN - Afghan Afghani"],
    XCD: ["AG", "XCD - East Caribbean Dollar"],
    ALL: ["AL", "ALL - Albanian Lek"],
    ANG: ["AN", "ANG - Netherlands Antillean Guilder"],
    AMD: ["AM", "AMD - Armenian Dram"],
    AOA: ["AO", "AOA - Angolan Kwanza"],
    ARS: ["AR", "ARS - Argentine Peso"],
    AUD: ["AU", "AUD - Australian Dollar"],
    AZN: ["AZ", "AZN - Azerbaijan New Manat"],
    BAM: ["BA", "BAM - Bosnian Convertible Mark"],
    BBD: ["BB", "BBD - Barbados Dollar"],
    BDT: ["BD", "BDT - Bangladeshi Taka"],
    XOF: ["BE", "XOF - CFA Franc"],
    BGN: ["BG", "BGN - Bulgarian Lev"],
    BHD: ["BH", "BHD - Bahraini Dinar"],
    BIF: ["BI", "BIF - Burundian Franc"],
    BMD: ["BM", "BMD - Bermudian Dollar"],
    BND: ["BN", "BND - Bruneian Dollar"],
    BOB: ["BO", "BOB - Bolivian Boliviano"],
    BRL: ["BR", "BRL - Brazilian Real"],
    BSD: ["BS", "BSD - Bahamian Dollar"],
    NOK: ["BV", "NOK - Norwegian Krone"],
    BWP: ["BW", "BWP - Botswanan Pula"],
    BYR: ["BY", "BYR - Belarusian Ruble"],
    BZD: ["BZ", "BZD - Belizean Dollar"],
    CAD: ["CA", "CAD - Canadian Dollar"],
    CDF: ["CD", "CDF - Congolese Franc"],
    XAF: ["CF", "XAF - Central African CFA franc"],
    CHF: ["CH", "CHF - Swiss Franc"],
    CLP: ["CL", "CLP - Chilean Peso"],
    CNY: ["CN", "CNY - Chinese Yuan"],
    COP: ["CO", "COP - Colombian Peso"],
    CRC: ["CR", "CRC - Costa Rican Colon"],
    CUP: ["CU", "CUP - Cuban Peso"],
    CVE: ["CV", "CVE - Cape Verdean Escudo"],
    CYP: ["CY", "CYP - Cypriot Pound"],
    CZK: ["CZ", "CZK - Czech Koruna"],
    DJF: ["DJ", "DJF - Djiboutian Franc"],
    DKK: ["DK", "DKK - Danish Krone"],
    DOP: ["DO", "DOP - Dominican Peso"],
    DZD: ["DZ", "DZD - Algerian Dinar"],
    ECS: ["EC", "ECS - Ecuadorian Sucre"],
    EEK: ["EE", "EEK - Estonian Kroon"],
    EGP: ["EG", "EGP - Egyptian Pound"],
    ETB: ["ET", "ETB - Ethiopian Birr"],
    EUR: ["FR", "EUR - Euro"],
    FJD: ["FJ", "FJD - Fijian Dollar"],
    FKP: ["FK", "FKP - Falkland Islands Pound"],
    GBP: ["GB", "GBP - British Pound"],
    GEL: ["GE", "GEL - Georgian Lari"],
    GGP: ["GG", "GGP - Guernsey Pound"],
    GHS: ["GH", "GHS - Ghanaian Cedi"],
    GIP: ["GI", "GIP - Gibraltar Pound"],
    GMD: ["GM", "GMD - Gambian Dalasi"],
    GNF: ["GN", "GNF - Guinean Franc"],
    GTQ: ["GT", "GTQ - Guatemalan Quetzal"],
    GYD: ["GY", "GYD - Guyanese Dollar"],
    HKD: ["HK", "HKD - Hong Kong Dollar"],
    HNL: ["HN", "HNL - Honduran Lempira"],
    HRK: ["HR", "HRK - Croatian Kuna"],
    HTG: ["HT", "HTG - Haitian Gourde"],
    HUF: ["HU", "HUF - Hungarian Forint"],
    IDR: ["ID", "IDR - Indonesian Rupiah"],
    ILS: ["IL", "ILS - Israeli Shekel"],
    INR: ["IN", "INR - Indian Rupee"],
    IQD: ["IQ", "IQD - Iraqi Dinar"],
    IRR: ["IR", "IRR - Iranian Rial"],
    ISK: ["IS", "ISK - Icelandic Krona"],
    JMD: ["JM", "JMD - Jamaican Dollar"],
    JOD: ["JO", "JOD - Jordanian Dinar"],
    JPY: ["JP", "JPY - Japanese Yen"],
    KES: ["KE", "KES - Kenyan Shilling"],
    KGS: ["KG", "KGS - Kyrgystani Som"],
    KHR: ["KH", "KHR - Cambodian Riel"],
    KMF: ["KM", "KMF - Comorian Franc"],
    KPW: ["KP", "KPW - North Korean Won"],
    KRW: ["KR", "KRW - South Korean Won"],
    KWD: ["KW", "KWD - Kuwaiti Dinar"],
    KYD: ["KY", "KYD - Caymanian Dollar"],
    KZT: ["KZ", "KZT - Kazakhstani Tenge"],
    LAK: ["LA", "LAK - Lao Kip"],
    LBP: ["LB", "LBP - Lebanese Pound"],
    LKR: ["LK", "LKR - Sri Lankan Rupee"],
    LRD: ["LR", "LRD - Liberian Dollar"],
    LSL: ["LS", "LSL - Basotho Loti"],
    LTL: ["LT", "LTL - Lithuanian Litas"],
    LVL: ["LV", "LVL - Latvian Lat"],
    LYD: ["LY", "LYD - Libyan Dinar"],
    MAD: ["MA", "MAD - Moroccan Dihram"],
    MDL: ["MD", "MDL - Moldovan Leu"],
    MGA: ["MG", "MGA - Malagasy Ariary"],
    MKD: ["MK", "MKD - Macedonian Denar"],
    MMK: ["MM", "MMK - Burmese Kyat"],
    MNT: ["MN", "MNT - Mongolian Tughrik"],
    MOP: ["MO", "MOP - Macau Pataca"],
    MRO: ["MR", "MRO - Mauritanian Ouguiya"],
    MTL: ["MT", "MTL - Maltese Lira"],
    MUR: ["MU", "MUR - Mauritian Rupee"],
    MVR: ["MV", "MVR - Maldivian Rufiyaa"],
    MWK: ["MW", "MWK - Malawian Kwacha"],
    MXN: ["MX", "MXN - Mexican Peso"],
    MYR: ["MY", "MYR - Malaysian Ringgit"],
    MZN: ["MZ", "MZN - Mozambican Metical"],
    NAD: ["NA", "NAD - Namibian Dollar"],
    XPF: ["NC", "XPF - CFP Franc"],
    NGN: ["NG", "NGN - Nigerian Naira"],
    NIO: ["NI", "NIO - Nicaraguan Cordoba"],
    NPR: ["NP", "NPR - Nepalese Rupee"],
    NZD: ["NZ", "NZD - New Zealand Dollar"],
    OMR: ["OM", "OMR - Omani Rial"],
    PAB: ["PA", "PAB - Panamanian Balboa"],
    PEN: ["PE", "PEN - Peruvian Sol"],
    PGK: ["PG", "PGK - Papua New Guinean Kina"],
    PHP: ["PH", "PHP - Philippine Peso"],
    PKR: ["PK", "PKR - Pakistani Rupee"],
    PLN: ["PL", "PLN - Polish Zloty"],
    PYG: ["PY", "PYG - Paraguayan Guarani"],
    QAR: ["QA", "QAR - Qatari Riyal"],
    RON: ["RO", "RON - Romanian Leu"],
    RSD: ["RS", "RSD - Serbian Dinar"],
    RUB: ["RU", "RUB - Russian Ruble"],
    RWF: ["RW", "RWF - Rwandan Franc"],
    SAR: ["SA", "SAR - Saudi Arabian Riyal"],
    SBD: ["SB", "SBD - Solomon Islander Dollar"],
    SCR: ["SC", "SCR - Seychellois Rupee"],
    SDG: ["SD", "SDG - Sudanese Pound"],
    SEK: ["SE", "SEK - Swedish Krona"],
    SGD: ["SG", "SGD - Singapore Dollar"],
    SKK: ["SK", "SKK - Slovak Koruna"],
    SLL: ["SL", "SLL - Sierra Leonean Leone"],
    SOS: ["SO", "SOS - Somali Shilling"],
    SRD: ["SR", "SRD - Surinamese Dollar"],
    STD: ["ST", "STD - Soa Tomean Dobra"],
    SVC: ["SV", "SVC - Salvadoran Colon"],
    SYP: ["SY", "SYP - Syrian Pound"],
    SZL: ["SZ", "SZL - Swazi Lilangeni"],
    THB: ["TH", "THB - Thai Baht"],
    TJS: ["TJ", "TJS - Tajikistani Somoni"],
    TMT: ["TM", "TMT - Turkmenistani Manat"],
    TND: ["TN", "TND - Tunisian Dinar"],
    TOP: ["TO", "TOP - Tongan Pa'anga"],
    TRY: ["TR", "TRY - Turkish Lira"],
    TTD: ["TT", "TTD - Trinidadian Dollar"],
    TWD: ["TW", "TWD - Taiwan New Dollar"],
    TZS: ["TZ", "TZS - Tanzanian Shilling"],
    UAH: ["UA", "UAH - Ukrainian Hryvnia"],
    UGX: ["UG", "UGX - Ugandan Shilling"],
    USD: ["US", "USD - US Dollar"],
    UYU: ["UY", "UYU - Uruguayan Peso"],
    UZS: ["UZ", "UZS - Uzbekistani Som"],
    VEF: ["VE", "VEF - Venezuelan Bolivar"],
    VND: ["VN", "VND - Vietnamese Dong"],
    VUV: ["VU", "VUV - Ni-Vanuatu Vatu"],
    YER: ["YE", "YER - Yemeni Rial"],
    ZAR: ["ZA", "ZAR - South African Rand"],
    ZMK: ["ZM", "ZMK - Zambian Kwacha"],
    ZWD: ["ZW", "ZWD - Zimbabwean Dollar"]
};